package stack

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mk-amorson/Octopus/installer/internal/docker"
	"github.com/mk-amorson/Octopus/installer/internal/state"
)

// composeTemplate is the docker compose config we render into the extracted
// source tree. It builds apps/web/Dockerfile with the subpath + version
// baked in, binds the host port, and passes runtime env vars (token etc).
//
// Keep runtime secrets out of `build.args` — those get baked into the
// image and into the compose file on disk. `environment:` values also
// live in the compose file, so treat OCTOPUS_TOKEN as "secret from the
// network, not secret from root on this host".
const composeTemplate = `# Generated by the Octopus installer. Do not edit by hand —
# changes here are wiped on the next 'octopus install' or 'octopus update'.
services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        OCTOPUS_BASE_PATH: "%s"
        OCTOPUS_VERSION: "%s"
    image: octopus-web:%s
    container_name: %s
    restart: unless-stopped
    environment:
      OCTOPUS_TOKEN: "%s"
    ports:
      - "%s:%d:%d"
`

// Render writes docker-compose.yml into the source tree for the given config.
// The file is rewritten on every install/update, which is the whole point —
// host/port/subpath changes take effect without any manual editing.
func Render(srcDir string, c state.Config) error {
	content := fmt.Sprintf(
		composeTemplate,
		c.BasePath,
		c.Version,
		strings.TrimPrefix(c.Version, "v"),
		state.ContainerName,
		c.Token,
		c.Host,
		c.Port,
		state.ContainerPort,
	)
	p := filepath.Join(srcDir, "docker-compose.octopus.yml")
	// 0600: compose file now contains the admin token in plaintext.
	// Anyone with shell access on the box could already read it, but
	// drop world/group read to cut the exposure surface.
	return os.WriteFile(p, []byte(content), 0o600)
}

// composeFile is the relative path of the rendered compose file inside
// srcDir. Kept in one place so every caller uses the same `-f` argument.
const composeFile = "docker-compose.octopus.yml"

// Build runs `docker compose build` for the web service. It's the slow step
// on a fresh install (pulls node:20-alpine, runs pnpm install, runs next
// build), and `docker compose up` would do it implicitly — we call it
// explicitly so failures surface before we try to start anything.
func Build(srcDir string) error {
	return docker.Compose(srcDir, state.ComposeProject, "-f", composeFile, "build", "web")
}

// Up starts the web service in detached mode. Idempotent — if the container
// is already running on the same config, docker compose is a no-op.
func Up(srcDir string) error {
	return docker.Compose(srcDir, state.ComposeProject, "-f", composeFile, "up", "-d", "web")
}

// Down stops and removes the container but keeps the built image around, so
// `octopus start` after `octopus stop` is cheap.
func Down(srcDir string) error {
	return docker.Compose(srcDir, state.ComposeProject, "-f", composeFile, "down")
}

// DownHard is Down + removes volumes. Used by uninstall only.
func DownHard(srcDir string) error {
	return docker.Compose(srcDir, state.ComposeProject, "-f", composeFile, "down", "-v")
}

// RemoveImage drops the built image so `octopus uninstall` leaves no trace
// behind. Best-effort — if the image is already gone (fresh install aborted
// before build, manual cleanup) we don't care.
func RemoveImage(version string) {
	tag := "octopus-web:" + strings.TrimPrefix(version, "v")
	_, _ = docker.RunQuiet("", "image", "rm", tag)
}

// Running reports whether the web container is currently up, for status/start.
func Running() (bool, error) {
	out, err := docker.ComposeQuiet("", state.ComposeProject, "ps", "--status", "running", "--services")
	if err != nil {
		// docker compose ps returns non-zero only when the project doesn't
		// exist yet, which is just "not running" from our perspective.
		return false, nil
	}
	return strings.Contains(strings.TrimSpace(out), "web"), nil
}
